# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-05 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeanimal', models.CharField(max_length=32)),
                ('raça', models.CharField(max_length=32)),
                ('costumes', models.CharField(max_length=122)),
                ('alimentação', models.CharField(max_length=122)),
                ('gosta', models.CharField(max_length=122)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
