# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-07 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('endereço', models.CharField(max_length=150)),
                ('casa', models.CharField(max_length=20)),
                ('filhos', models.IntegerField()),
                ('horas', models.IntegerField()),
                ('idade1', models.IntegerField()),
            ],
        ),
    ]
