# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pessoas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Animais'),
        ),
    ]
