# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-11 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210209_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoas',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='pessoas',
            name='user',
        ),
        migrations.AddField(
            model_name='animais',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='animais',
            name='nomepessoal',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Pessoas',
        ),
    ]
