# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210211_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='telefone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='animais',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animais'),
        ),
    ]
